---
- name: Pousser une configuration sur Cisco IOS
  hosts: 192.168.254.29
  gather_facts: no

  tasks:
    - name: Changer le hostname
      cisco.ios.ios_config:
        lines:
          - hostname TEST-SWITCH