---
- name: Test commandes Aruba
  hosts: all
  gather_facts: no

  tasks:
    - name: Afficher la version du switch Aruba
      aruba_command:
        commands:
          - show version
      register: aruba_result

    - name: Afficher la running-config
      aruba_command:
        commands:
          - show running-config
      register: aruba_running

    - name: Afficher les résultats
      debug:
        var: aruba_result.stdout_lines

    - name: Afficher la running-config
      debug:
        var: aruba_running.stdout_lines