---
- name: Test commandes Cisco IOS
  hosts: all
  gather_facts: no

  tasks:
    - name: Afficher la version du switch Cisco
      ios_command:
        commands:
          - show version
      register: cisco_result

    - name: Afficher la configuration running
      ios_command:
        commands:
          - show running-config
      register: cisco_running

    - name: Afficher les résultats
      debug:
        var: cisco_result.stdout_lines

    - name: Afficher la running-config
      debug:
        var: cisco_running.stdout_lines