---
- name: Test connexion SSH Cisco
  hosts: 192.168.254.29
  gather_facts: no

  tasks:
    - name: Afficher la version du switch
      cisco.ios.ios_command:
        commands:
          - show version
      register: result

    - name: Afficher le résultat
      debug:
        var: result.stdout_lines