---
- name: Download running config from Cisco IOS-XE device (via ios_facts)
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    config_output_file: "{{ output_file | default('running_config.txt') }}"

  tasks:
    - name: Collect running config with ios_facts
      cisco.ios.ios_facts:
        gather_subset: config
      register: ios_facts_result



    - name: Print running config to stdout
      debug:
        msg: "{{ ios_facts_result.ansible_facts.ansible_net_config | default('') }}"